apiVersion: v1
kind: Service
metadata:
    name: "examplek8scluster36064ec-e960"
    labels:
        app: "examplek8scluster36064ec-e960"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "examplek8scluster36064ec-e960"